In [1]:
import pandas as pd

In [2]:
items_compra = ['steel', 'memento','black magic ore', 'coal', 'activity stone', 'stick mucus', 
             'gold sand','awakening potion','immortal heart','orc claw', 'mercury', 
             'slow atk alloy', 'glass bead','heroic emblem','skel-bone', 'earth mastery alloy', 
             'hand of god']
valores_compra = [65, 180, 20, 95, 10, 180, 50, 15, 200, 2, 60, 10, 250, 2, 70, 10, 300]
zeny_compra = [764, 405, 800, 1910, 18260, 324, 971, 2500, 330, 152835, 1421, 24670, 524, 
               37625, 587, 28429, 737]
vaceraxe = [items_compra, valores_compra, zeny_compra]
vaceraxe

[['steel',
  'memento',
  'black magic ore',
  'coal',
  'activity stone',
  'stick mucus',
  'gold sand',
  'awakening potion',
  'immortal heart',
  'orc claw',
  'mercury',
  'slow atk alloy',
  'glass bead',
  'heroic emblem',
  'skel-bone',
  'earth mastery alloy',
  'hand of god'],
 [65, 180, 20, 95, 10, 180, 50, 15, 200, 2, 60, 10, 250, 2, 70, 10, 300],
 [764,
  405,
  800,
  1910,
  18260,
  324,
  971,
  2500,
  330,
  152835,
  1421,
  24670,
  524,
  37625,
  587,
  28429,
  737]]

In [3]:
vacervalor = pd.DataFrame({'Items':items_compra, 'Quantidades':valores_compra, 'Zeny':zeny_compra})

In [4]:
vacervalor

                  Items  Quantidades    Zeny
0                 steel           65     764
1               memento          180     405
2       black magic ore           20     800
3                  coal           95    1910
4        activity stone           10   18260
5           stick mucus          180     324
6             gold sand           50     971
7      awakening potion           15    2500
8        immortal heart          200     330
9              orc claw            2  152835
10              mercury           60    1421
11       slow atk alloy           10   24670
12           glass bead          250     524
13        heroic emblem            2   37625
14            skel-bone           70     587
15  earth mastery alloy           10   28429
16          hand of god          300     737

In [16]:
vacervalor['Multiplicado'] = vacervalor['Quantidades'] * 180

In [17]:
totalzeny = (vacervalor['Multiplicado'] * vacervalor['Zeny'])

In [18]:
valortotal = totalzeny.sum()
print(valortotal)

378601200

In [19]:
vacervalor

                  Items  Quantidades    Zeny  Multiplicado
0                 steel           65     764         11700
1               memento          180     405         32400
2       black magic ore           20     800          3600
3                  coal           95    1910         17100
4        activity stone           10   18260          1800
5           stick mucus          180     324         32400
6             gold sand           50     971          9000
7      awakening potion           15    2500          2700
8        immortal heart          200     330         36000
9              orc claw            2  152835           360
10              mercury           60    1421         10800
11       slow atk alloy           10   24670          1800
12           glass bead          250     524         45000
13        heroic emblem            2   37625           360
14            skel-bone           70     587         12600
15  earth mastery alloy           10   28429          1800
16          hand of god          300     737         54000

In [40]:
60*25

1500